### ISSUE TITLE
这么牛逼的？

### ISSUE THREAD

**Issue by WRTY1** [Nikaidou-Shinku/web-homework#1]
现在才开始写？

**Comment by Nikaidou-Shinku** [comment]
前段时间太忙辣，补大物实验，四级，体测，微积分考试，全部堆一起了。反正二十号截止之前，能写多少就交多少上去叭。

**Comment by By-Ha** [comment]
🤡您不是说自己完全不复习么

**Comment by Nikaidou-Shinku** [comment]
考试堆一起了没时间写代码跟复习有什么关系

**Comment by By-Ha** [comment]
我直接交了kana，樂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月21日(周二) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Nikaidou-Shinku/web-homework] 这么牛逼的？ (Issue #1)




 考试堆一起了没时间写代码跟复习有什么关系

**Comment by Nikaidou-Shinku** [comment]
写完了，开始整报告了，脑壳疼
